### ISSUE TITLE
how to use ssl in config?

### ISSUE THREAD

**Issue by SoftrainHere** [ssi-anik/laravel-amqp#1]
Hi I am using mq in aws  and struggling with tiny problem

'stream_socket_client(): Unable to connect to amqps://xxx.mq.ap-northeast-2.amazonaws.com:5671 (Unable to find the socket transport "amqps" - did you forget to enable it when you configured PHP?)'

Where should I define ssl option for error above??
Help me please~~

**Comment by ssi-anik** [comment]
Did you read the documentation? 

- amqp.connections.*.connection.class denoting the underlying Amqp connection to be used. By default, it uses lazy connection. You can change it to any implementation of PhpAmqpLib\Connection\AbstractConnection.
- amqp.connections.*.connection.hosts can have multiple host configuration. Each host config must contain host , port, user, password keys. It can also contain vhost which is optional. Lazy connections cannot have more than one host configuration otherwise it'll throw error.
- You can also pass optional array of parameters through amqp.connections.*.connection.options when creating an instance of amqp.connections.*.connection.class internally.

**Comment by seokman-hong** [comment]
stream_socket_client(): Unable to connect to amqps://xxxxxxx.mq.ap-northeast-2.amazonaws.com:5671 (Unable to find the socket transport "amqps" - did you forget to enable it when you configured PHP?)

I got this now....
I really have no idea about this....
What really should I do for this??
